hyperskill_project:
  id: 50
  ide_files: https://stepik.org/media/attachments/lesson/209941/additional_files.json
  is_template_based: false
stages:
- id: 271
  step: 5413
- id: 272
  step: 5414
- id: 273
  step: 5415
- id: 274
  step: 5416
- id: 275
  step: 5417
- id: 276
  step: 5418
topics:
  0:
  - title: Introduction to OOP
    theory_id: 3614
  - title: Units of information
    theory_id: 6865
  - title: Computer algorithms
    theory_id: 4953
  - title: The big O notation
    theory_id: 4991
  - title: Data structures
    theory_id: 5161
  - title: Pseudocode basics
    theory_id: 8228
  - title: Complex constructions in pseudocode
    theory_id: 8233
  - title: Hash table
    theory_id: 5364
  - title: Fixed-size array
    theory_id: 7255
  - title: Dynamic array
    theory_id: 5357
  - title: Binary numbers
    theory_id: 5544
  - title: Immutability
    theory_id: 7929
  - title: Command line overview
    theory_id: 6577
  - title: What is an exception
    theory_id: 3497
  - title: NPE
    theory_id: 1945
  - title: Algorithms in Java
    theory_id: 3540
  - title: Generic programming
    theory_id: 3492
  - title: Generics and Object
    theory_id: 3493
  - title: Generic methods
    theory_id: 3606
  - title: Hash table in Java
    theory_id: 6945
  - title: What are collections
    theory_id: 3770
  - title: ArrayList
    theory_id: 3567
  - title: IDE
    theory_id: 3805
  - title: Introduction to Java
    theory_id: 3500
  - title: Basic literals
    theory_id: 3522
  - title: Overview of the basic program
    theory_id: 3521
  - title: Printing data
    theory_id: 3749
  - title: Types and variables
    theory_id: 3518
  - title: Primitive and reference types
    theory_id: 5035
  - title: Array
    theory_id: 3511
  - title: Comments
    theory_id: 3520
  - title: Naming variables
    theory_id: 3513
  - title: Arithmetic operations
    theory_id: 3519
  - title: Write, compile and run
    theory_id: 3739
  - title: JVM, JRE and JDK
    theory_id: 3499
  - title: Sizes and ranges
    theory_id: 3532
  - title: Type casting
    theory_id: 3510
  - title: Running programs on your computer
    theory_id: 3746
  - title: Scanning the input
    theory_id: 3603
  - title: Errors in programs
    theory_id: 3536
  - title: Integer types and operations
    theory_id: 3565
  - title: Boolean and logical operations
    theory_id: 3516
  - title: Relational operators
    theory_id: 3512
  - title: Increment and decrement
    theory_id: 5008
  - title: Characters
    theory_id: 3514
  - title: String
    theory_id: 3523
  - title: Conditional statement
    theory_id: 3503
  - title: The for-loop
    theory_id: 3505
  - title: The while and do-while loops
    theory_id: 3498
  - title: Branching statements
    theory_id: 3507
  - title: Ternary operator
    theory_id: 3506
  - title: Iterating over arrays
    theory_id: 3602
  - title: Defining methods
    theory_id: 3590
  - title: The main method
    theory_id: 3489
  - title: Defining classes
    theory_id: 3618
  - title: Package
    theory_id: 3621
  - title: Constructor
    theory_id: 3535
  - title: Objects
    theory_id: 4727
  - title: Instance methods
    theory_id: 3495
  - title: Access modifiers
    theory_id: 3589
  - title: Getters and setters
    theory_id: 3599
  - title: Inheritance
    theory_id: 3583
  - title: Protected modifier
    theory_id: 6692
  - title: Referencing subclass objects
    theory_id: 3585
  - title: The Object class
    theory_id: 3596
  - title: LocalDate
    theory_id: 3592
  - title: LocalTime
    theory_id: 3593
  - title: LocalDateTime
    theory_id: 3617
  - title: Boxing and unboxing
    theory_id: 3595
  - title: IntelliJ IDEA
    theory_id: 3801
